import { Antonio, Inter } from "next/font/google";
import "./globals.css";
import Transition from "@/components/Transition";


const antonio = Antonio({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${antonio.className} bg-black`}>
        <Transition>{children}</Transition>
      </body>
    </html>
  );
}
